site_name: Clustercast
nav:
    - 'Home': index.md
    - 'Quick Start Examples':
        - 'Local (Single-Series)': example_single-series.md
        - 'Global (Multi-Series)': example_multi-series.md
        - 'Using a Custom Regressor': example_custom-regressor.md
    - 'Clustercast API':
        - 'DirectForecaster': DirectForecaster.md
        - 'RecursiveForecaster': RecursiveForecaster.md
theme: 
    name: readthedocs
    prev_next_buttons_location: None
    navigation_depth: 3
    collapse_navigation: True
    titles_only: True